# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aurang
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: auction-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auction-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          path: /auction
          method: POST
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - httpApi:
          path: /auctions
          method: GET
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - httpApi:
          path: /auction/{id}
          method: GET
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - httpApi:
          path: /auction/{id}/bid
          method: PATCH

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
